model:
  model_id: google/paligemma-3b-mix-224
data:
  train_csv: processed_dataset/train.csv
  val_csv: processed_dataset/val.csv
  test_csv: processed_dataset/test.csv
  dataset_path: dataset/resized
  max_train_samples: 0
  max_val_samples: 0
evaluation:
  eval_during_training: true
  generate_max_length: 128
  min_length: 20
  num_beams: 4
lora:
  r: 8
  lora_alpha: 64
  lora_dropout: 0.1
  target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
output:
  output_dir: paligemma_tsn_qlora
prompt:
  # Available prompt options:
  # 'Caption this image:'
  # 'Describe this image in detail:'
  # 'What can you see in this remote sensing image?'
  # 'Provide a detailed description of this aerial/satellite image:'
  # 'Describe all the objects and features visible in this remote sensing image:'
  # 'What do you see in this aerial photograph?'
  input_prompt: 'Describe all the objects and features visible in this remote sensing image:'
training:
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 1.0e-06
  mixed_precision: true
  num_epochs: 30
  weight_decay: 0.05
  label_smoothing: 0.1
  use_wandb: true

wandb:
  run_name: tsn-inception_v3-lora-r8
  project: 2697134-tsn-paligemma-project
  log_val_loss: true
tsn:
  # Backbone options: resnet18, resnet50, resnet101, resnet152, inception_v3, efficientnet_b0, efficientnet_b3
  backbone: inception_v3
  feature_dim: 2048
  pretrained: true
  projection_dim: 1408
  segment_scales:
  - - 1
    - 1
  - - 2
    - 2
  use_attention: true
  # TSN integration method: 'replace', 'combine', 'adapter', 'direct', or 'enhanced'
  integration_method: enhanced
  # Mixing ratios for combining original vision tower output with TSN features
  # Higher values for original_ratio reduce the risk of triggering safety mechanisms
  # For forward pass (training)
  original_ratio: 0.5
  tsn_ratio: 0.5
  # For generate (inference)
  gen_original_ratio: 0.6
  gen_tsn_ratio: 0.4
